### ISSUE TITLE
Venue onboarding tweaks 

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#147]
Following on from our walkthrough #145, there are a small number of high priority points to be addressed for the venue onboarding:
+ [x] Add address field to the 'Create venue' form https://github.com/club-soda/club-soda-guide/issues/25
  + [x] Remove 'Look up address' link for now, will be reinstated in #100 
+ [x] Remove Website and phone number fields from the initial venue creation form
+ [x] Add social media handles input areas to venue page as per #25 
+ [x] Add mocktails to Club Soda score: https://github.com/club-soda/club-soda-guide/issues/61#issuecomment-436705095
+ [x] Add 'Add a product' link to venue page as per #146
+ [x] Make venue description field a textarea #128 and https://github.com/dwyl/fields/issues/20
+ [x] Link Jussi's email to the 'Can't find my product' dialogue https://github.com/club-soda/club-soda-guide/issues/92

**Comment by jussi-club-soda** [comment]
Thumbs up
