### ISSUE TITLE
CMS Spike

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#5]
As a Club Soda owner
I would like to determine what the most appropriate CMS is that meets my needs early on in this project 
So that there is a low risk of having to change the foundation of the website at a  later date.

## Tasks
+ [x] Initial call review requirements via designs
+ [x] Write up requirements list from the call
+ [x] Investigate various CMS options
+ [x] dwyl team call to discuss options
+ [x] Write up recommendation

**Comment by Danwhy** [comment]
### CMS Requirements
- [ ] Custom types (venues, brands etc.)
- [ ] Structure of pages and resources/types (drinks can belong to both brands and venues)
- [ ] Good search functionality
- [ ] Access control - Either:
  - [ ] Fine grained CMS access (ie. restrict individual inputs)
  or
  - [ ] Ability to update pages from outside the CMS (Headless CMS functionality)
- [ ] Image uploads
- [ ] Ability to export data (preferably as csv) (low priority)

**Comment by Danwhy** [comment]
Price is something else we will want to take into account when weighing up the pros and cons of each CMS in our recommendation. Some of the options are free, but others will cost (although these will include database hosting).

Is there a budget for the CMS?

**Comment by Danwhy** [comment]
Shortlist of CMS candidates to look into further

* Wagtail - python based
* Apostrophe - node.js based

* Various Headless CMSs - These are CMSs that separate the back and front end, meaning we would have more flexibility in how we display, and sometimes create the data (With some, we are able to upload data to the CMS straight from a form on our site, which would be useful for giving venues access to update their information). Can be used with any backend, or in some cases, no backend.
  * Contentful
  * Prismic
  * ButterCMS
  * GraphCMS
  * Directus

@nelsonic, do you have any initial thoughts on, or experience with, any of the above? Any recommendations of others I haven't mentioned?

**Comment by ctrembath** [comment]
Hi @Danwhy 

Yes there is a small budget for CMS, can you give a ballpark idea of how much it would be per month / year?

**Comment by Danwhy** [comment]
@ctrembath They range from $15/month to $83/month for the basic plans, which would likely be enough  for the MVP, but then scale with amount of data/users. I'l make sure to include cost as one of the parameters in my research though (eg. the $83/month CMS doesn't seem to offer any more features than any of the others, so I probably wouldn't recommend it)

**Comment by nelsonic** [comment]
## Wagtail...?

It _should_ be "safe to assume" that https://wagtail.io is _made using_ the Wagtail CMS:
it's _unclear_ from: https://builtwith.com/?https%3a%2f%2fwagtail.io ...
what is clear is that they are using a "Kitchen Sink" approach:
https://builtwith.com/detailed/wagtail.io
![wagtail-cms-built-with](https://user-images.githubusercontent.com/194400/45421048-bb0d9280-b683-11e8-839a-17a2da2a1ffe.png)
![wagtail-cms-built-with-2](https://user-images.githubusercontent.com/194400/45421049-bcd75600-b683-11e8-8e31-8267b3889fa0.png)


The https://webhint.io stats for the https://wagtail.io website: ***148 errors***:
![wagtail-cms-webhint-errors](https://user-images.githubusercontent.com/194400/45421940-98c94400-b686-11e8-8fb7-a6189b160e28.png)

Lighthouse Score: 62% for accessibility and 67% for performance.
![wagtail-cms-lighthouse-score](https://user-images.githubusercontent.com/194400/45421692-c661bd80-b685-11e8-8cb7-f592d1215754.png)
![wagtail-cms-lighthouse-accessibility](https://user-images.githubusercontent.com/194400/45421698-c82b8100-b685-11e8-8834-1aa13d7ab85d.png)
![wagtail-cms-lighthouse-perf](https://user-images.githubusercontent.com/194400/45421699-ca8ddb00-b685-11e8-87bb-2a225b1c5c27.png)

https://cssstats.com/stats?url=https%3A%2F%2Fwagtail.io
![wagtail-cms-css-stats](https://user-images.githubusercontent.com/194400/45421704-cd88cb80-b685-11e8-8fac-2d5f2bb48dc4.png)


> We (@dwyl) have used Wagtail in the past because the client (NHS) _forced_ us to. 🔫 
> We subsequently spent (wasted) 2 sprints trying to extend and optimise it ⏳ 
> what the project(s) needed was something _much simpler_ and more flexible from the start. 🏍 

If the CMS does not _optimise_ for accessibility or performance "_out-of-the-box_"
we will spend all our time building with the CMS only for our end-user's time to be _wasted_
with slow page-loads and inaccessible content.

**Comment by nelsonic** [comment]
I feel like we have approached this with an invalid _hypothesis_: "_determine the most appropriate CMS_"
which has lead us to _assume_ that we _need_ a _specific_ CMS for the project to succeed.
What we need _instead_ is an _clear understanding_ of the **Critical Success Factor**s in the project.

The **questions** we _should_ be asking/answering are:

## 1. Users?

1. Who are the "**users**" of the Website? 
  + The "**Piqued Drinker**" - someone who is _already_ aware and or has a desire to be more mindful of their drinking. The _vast_ majority users of the website are the "mindful drinkers". 
    + Are the drink buyers further segmented? 
    e.g: http://howtorunapub.co.uk/uk-pub-customer-demographics-behaviours/
      + Students / "Young & Free"
      + Nesting couples (no kids)
      + Affluent Young Professionals (no kids)
      + Families (with kids)
      + Mums & Dads (not taking kids to pub)
      + "Empty Nesters" (older people whose kids have left home) 
  + Venue/**Pub Owner**/Manager - the people for whom incremental patrons (customers) will have a _meaningful_ impact on bottom line.
  + Product/Brand Manager
  + Club Soda _Admin_

> Do we have a "persona" for each type of user for the Website or at least clearly defined "roles"?
(_so that we can write user stories for each one? and can we have a **`label`** fore each user?_)
Are each of these these users "active" or "passive" (_do they **create** or simply **consume** content_?) do we _want_ them to create content? (_will that drive revenue for Pubs/Brands and "CS"_)

## 2. Content?  

2. **What** are the primary content types we want to store for the project _and_: 
  2.a ***Who*** is going to _input_ the data for each content type. 
    i. will content be _initially_ created by club-soda "core" team and then updated/maintained by the Venues/Brands?
    ii. Is there already a **workflow** (_preferably diagram_) illustrating how content is created/updated. If not, can we _create/define_ one?
    iii. what are the "***challenges***" to making content editable/maintainable by the stakeholders who benefit the _most_ from keeping it fresh/relevant?
  2.b **What** (micro)format do we want to display the content in to maximise it's usefulness 
  both to the target _end-users_ and search-engines.
  1.c **How** will the content be kept "_fresh_" (_relevant_) so that search engine spiders 
  give it a higher ranking than _competing_ content? 

## 3. _Secondary_ Content?

3. What are the _related_ (_secondary_) content types for each of the _primary_ content types.
For _example_: 
  + ***Product*** ratings/reviews?
  + ***Venue*** ratings/reviews?
  + ***Event*** rating/review? (_e.g: Mindful Drinking Festival_ https://mindfuldrinkingfestival.com/mindful-drinking )
  + ***User Images***? _note_: we do not need to _store_ the images, we could simply store a _reference_ to them e.g: link to the Twitter/Instagram post where the drink/venue/event was tagged/mentioned.

## 4. Data Storage? https://github.com/club-soda/club-soda-guide/issues/85 (Database Setup)

4.  **What** is the most _effective_ way of _storing_ each content type?
  e.g: is a Document Database best? or a ("traditional") _Relational_ Database?
  do we need "flexibility" or "consistency"?

https://www.getthedata.com/open-pubs >> [open_pubs.csv.zip](https://github.com/club-soda/club-soda-guide/files/2386426/open_pubs.csv.zip) (Sample) Last update: August 2018

## 5. Metrics?

5. Which _Metrics_ to Track? Page Views vs. Engagement and _Action_?

Is the objective of the Website to get more ***page views***? or to _help_ people ***change*** their **behaviour**?
Viewing the page is the _first_ step, but it's not in itself a good metric to focus on.

A **_much_ better** metric would be to track "completed actions"  of the **user _journey_** through the website. e.g: 
+ a prospective mindful drinker (MD) "lands" on a specific product ("landing") page after searching for a specific beverage on Google: "***Peach Bellini Mocktail***" (_insert name of **real** drink here!_)
+ The website detects that the MD is on a mobile device and asks: "_would you like to find a venue near you that stocks this drink?_" 
  + Request access to **device location** http://diveinto.html5doctor.com/geolocation.html
  + Show postcode lookup input. (_Dan has built this for TC before_)
+ Display **list** of venues which stock/serve this drink.
  + Bonus Level: show [view on map] link next to each venue in list.
+ User clicks on [view on map] link 
+ User visits venue
+ User leaves a review for the product and/or venue

Do we have stats for the annual expenditure of mindful (_or non-alcoholic_) drink consumers? e.g:
https://www.statista.com/statistics/597628/average-total-spend-per-year-in-pubs-uk/
![image](https://user-images.githubusercontent.com/194400/45594557-d551b400-b994-11e8-8bb0-d558f18d98dc.png)

What are the "biggest concerns" for the Pubs? (_what keeps them "up at night"_?)
And _how_ can we help them to be successful instead of going out of business?
https://www.bbc.com/news/business-43492043
![image](https://user-images.githubusercontent.com/194400/45594569-324d6a00-b995-11e8-84b1-1eeaf75578ec.png)
> **Note**: I'm _not_ suggesting that "success" for a pub is selling people **more _alcohol_**.

We should seek to understand the following metrics:
+ **Who** are the most loyal customers ("regulars") and do they drink alcohol more often than non-alcoholic drinks?
  + Are they tracking the increase/decline in these regulars?
+ **Who** are the ***new*** customers driving ***new*** demand/growth?
+ What is the percentage of sales of Alcoholic drinks, Non-Alcoholic drinks, food (meals) and snacks?
  + What is the _profitability_ of each product category?
  + How are these product categories growing/shrinking?
+ Do people drinking _non-alcoholic_ drinks spend more or less on snacks/food in the venue?

## Feedback Loop?

+ How many of the various types of users are signed up to receive the **CS newsletter**?
+ How many of the users are _regular_/_repeat_ visitors to the website?
  + What is the percentage of people who visit once and do _not_ click on any call-to-action?
  + How many visits per month is the average?
+ Do users give feedback on products which can be "re-packaged" and passed on to the brands?

> **Note**: this is a ***non-exhaustive*** list; it's a "starting point" of the questions we should be seeking clarity on so that we have a "SMART" goal for the project (_beyond "build a CMS website"_).

**Comment by iteles** [comment]
Thank you for these @nelsonic, they'll be very enlightening. We have a good view of content types for example, but it will be very useful to have these catalogued here and we have discussed very little on metrics so far. 👍 

I have split these out into their own issues (linked above) for clarity of further discussions.
