### ISSUE TITLE
Update Dev Guide to include All Steps To Run on Localhost

### ISSUE THREAD

**Issue by nelsonic** [club-soda/club-soda-guide#512]
At present the Dev Guide has a some useful info ✅ _however_ it is _incomplete_.
[https://github.com/club-soda/club-soda-guide#dev-guide](https://github.com/club-soda/club-soda-guide/tree/818b01c1c8c6aee4ff02f1cfb199ba0519f269da#dev-guide)
If you can help make `localhost` setup _seamless_ for the ["**_next_ dev**"](https://blog.codinghorror.com/coding-for-violent-psychopaths/) working on this, please comment!

# Todo
+ [x] ensure that **_all_ steps** necessary for running the app on `localhost` are covered including
  + Ensure you have all the necessary dependencies
    + [x] Elixir
    + [x] Elm
    + [x] PostgreSQL
    + [x] Question: can we streamline this installation? https://github.com/dwyl/learn-docker/issues/15 @SimonLab 
  + [x] Get the code: **`git clone git@github.com:club-soda/club-soda-guide.git`**
  + [x] Create **`.env`** file with necessary environment variables.
    + [x] show a _sample_ `.env` file with the required environment variables
    + [x] advise people how to get the _actual_ variables by viewing them on [Heroku](https://github.com/dwyl/learn-environment-variables#environment-variables-on-heroku) 
    (_this ensures that access to the environment variables is controlled by access to Heroku i.e. if people are in the deployment group they are authorised to view the secret keys ... please do not share environment variables via email or chat._)
+ [x] Install dependencies: **`mix deps.get`**
+ [x] Create the database: **`mix ecto.create`**
+ [x] Run seeds/scripts to import data. @Danwhy / @RobStallion if you can add some insight (_specific steps_) on this today it would be really helpful. (_a comment here is enough, thanks!_)
+ [x] Run the application on your `localhost`: **`mix phx.server`**
+ [x] Visit http://localhost:4000 in your web browser. you should expect to see:
![image](https://user-images.githubusercontent.com/194400/55151100-658f6380-5145-11e9-93c4-dd2c8627cb2e.png)

**Comment by nelsonic** [comment]
Wrote an _easy_ script to run in the browser console to get all the current environment variables from a Heroku App without having to copy-paste each one. see: https://github.com/dwyl/learn-heroku/issues/35

**Comment by nelsonic** [comment]
If you run the [script](https://github.com/dwyl/learn-heroku/issues/35) to collate the Environment Variables from the Heroku Staging App for use on `localhost` don't forget to remove the `DATABASE_URL` and `HEROKU_POSTGRESQL` variables to avoid attempting to write data to the Heroku PostgreSQL database. 
A _revised_ script is therefore: https://github.com/dwyl/learn-heroku/issues/35#issuecomment-480075887

Furthermore, given that we are attempting to test the app on `localhost`, we need to update the `URL` and `SITE_URL` variables to be `http://localhost:4000/` instead of whatever they are on Staging.
So the script we need to run in the browser console is:

```js
var keys = document.getElementsByClassName('config-var-key');
var vals = document.getElementsByClassName('config-var-value');
var vars = '';
for (var i = 0; i < keys.length - 1; i++) {
  var key = keys[i].value; 
  if (key && key !== 'DATABASE_URL' && key.indexOf('HEROKU_POSTGRESQL') === -1) {
    var index = (i == 0) ? 0 : i * 2; // cause there are two values for every key ... 🙄
    var value = (key === 'URL' || key === 'SITE_URL') ? 'http://localhost:4000' : vals[index].value;
    vars = vars + 'export ' + key + '=' + value + '\n';
  }
}
console.log(vars);
```

@RobStallion do you happen to know the reason for the existence of _two_ (_similar_) environment variables `URL` and `SITE_URL` ? (_can we remove one to avoid this question in future? Thanks!_ ☀️)

**Comment by nelsonic** [comment]
Updated time label as I am uncovering more to document as I do it ... ⏳

**Comment by nelsonic** [comment]
I've covered all of the items in the above checklist in #527 
(_except using Docker ... which I think is "advanced" and we can add it if manual setup is painful._)

**Comment by nelsonic** [comment]
Closing as the Dev Guide [**`dev-guide.md`**](https://github.com/club-soda/club-soda-guide/blob/master/dev-guide.md) is in **`master`** and in a _much_ better state. ✅
