### ISSUE TITLE
Venues can add required primary details

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#54]
As a venue setting up my listing on the Club Soda Guide,
I'd like to add my venue name and location, 
so I can proceed to the next stage of the on-boarding process

**Acceptance Criteria**
- [x] As a venue I see a field asking me for the name of my venue
- [x] As a venue I see a field asking me for the first line of the venue address
- [x] As a venue I see a field asking me for my postcode 
- [ ] My address is validated through a third party #100 
- [x] I am unable to progress with adding a listing if either name or location is blank
- [x] I am unable to progress if my venue is outside of the UK
- [x] Duplicate names of venues are accepted if the locations are different
- [x] Duplicate names of venues are rejected if there is already an identical instance in the database

**Comment by iteles** [comment]
There is a whole piece to discuss here around the creation of the listings. Once we involve three parties (admins, venues #54 and customers #80 plus claiming a listing #30), there are a lot of interactions and flows happening which we will need to iron out before we begin!

I would also note @jussi-club-soda and @ctrembath that the piece of work around allowing third parties (anyone apart from yourselves) to create venues is not small, so we will need to carefully consider prioritisation for this.

**Comment by jussi-club-soda** [comment]
@iteles yep - as I said at #80 I don't see that as feature we need/want. But I thought this would be pretty much the most basic feature of any listing site?

**Comment by iteles** [comment]
@jussi-club-soda Agreed, it wasn't until our conversation last week that I realised that being hands-off with the listing piece was one of your highest priorities. When I originally spoke to Clare about scope it wasn't top of mind for me.

Let's discuss tomorrow in light of estimatations! 😊

**Comment by Cleop** [comment]
gov.uk style guidelines for forms advises:

<img src="https://user-images.githubusercontent.com/16775804/46301240-b4e14680-c59d-11e8-90ae-56e60c3184a2.png" width=400px />

The gov.uk guidelines are created with meticulous attention to accessibility and good UX.

We may wish to consider substituting the use of asterisks on mandatory fields for the wording 'optional' on non-mandatory fields.

**Comment by iteles** [comment]
@jussi-club-soda Do you still want us to not accept venues outside the UK or without a valid UK post code?

**Comment by jussi-club-soda** [comment]
I guess for now we should keep this to UK addresses only.

**Comment by iteles** [comment]
@jussi-club-soda You mentioned in https://github.com/club-soda/club-soda-guide/issues/167 that you'd like a couple of venues in Dublin, Ireland to be listed. Is this still the case?

**Comment by jussi-club-soda** [comment]
No I think we'll leave Dublin out if their postcodes aren't doable...

**Comment by Cleop** [comment]
Response when you put in a venue that already exists at the same location:
![image](https://user-images.githubusercontent.com/16775804/51121447-5d46ae00-180f-11e9-93e0-777a2395a0c4.png)
We can change the error message if you've got something else in mind @jussi-club-soda
