### ISSUE TITLE
Image Optimisation

### ISSUE THREAD

**Issue by nelsonic** [club-soda/club-soda-guide#562]
# Story

As a person searching for "_The best low and no alcohol drinks_<sup>TM</sup>" on my mobile  as I wonder around town on a hot summer's day, I want to view the award winning Club Soda Guide website as quickly as possible so that I can find a refreshing drink at my nearest venue.

I _order_ to find my drink+venue as quickly as possible, I need the web page to _load_ as fast as possible. 

# _Technical_ Context

At present all the image assets have been uploaded to AWS S3 and served from CloudFront as they were received (_i.e. in their original dimensions, formats and compression_). This is done in the interest of _shipping_ and getting user feedback as fast as possible and to avoid ["premature optimisation"](http://wiki.c2.com/?PrematureOptimization).  Our mission is always:

1. Make it work.
2. Make it right.
3. Make it fast.

And so far we've been cycling through the first two steps to ensure everything works as expected.
> Note there is an ongoing debate in the software development community as to _when_ optimisations should occur: https://softwareengineering.stackexchange.com/questions/80084/premature-optimization-the-root-of-all-evil having _experienced_ first-hand how "premature optimisation" can delay shipping a project. 😞 We tend to opt for post-launch 🚀optimisations wherever possible to focus on the features users want/need and collecting their feedback _first_. 💬 
With that said, let's focus on the point of this issue: _**image optimisation** for a faster site_!

# Large Images Load _Slowly_ ... 🐌 

Running the ["Lighthouse Report"](https://developers.google.com/web/tools/lighthouse) in Google Chrome for https://www.clubsodaguide.com
we see that the single biggest area for improvement in site speed/performance is the size of images:

![image](https://user-images.githubusercontent.com/194400/56687494-5234d100-66ce-11e9-8a92-9887727cde9a.png)

Report: [to be uploaded shortly ...]

The main "opportunities" for improvement are around image formats/encoding and sizing:
![image](https://user-images.githubusercontent.com/194400/56687548-7690ad80-66ce-11e9-9a9c-e1c5d7c82793.png)

1. Serve images in next-gen formats
2. Efficiently encode images
3. Properly size images
4. Enable text compression
5. Defer offscreen images

You can run this report yourself simply opening Google Chrome and clicking the 

![image](https://user-images.githubusercontent.com/194400/56688629-1fd8a300-66d1-11e9-9f57-d07a56b4bb30.png)

All of these images can be _manually_ optimised by anyone with a web browser. 

Using the built-in free "Network" tab in Google Chrome Developer Tools, we can easily see which of the images are _huge_ and thus slowing down the loading of the page:
![club-soda-chrome-network-score-footer-image](https://user-images.githubusercontent.com/194400/56697704-4efa0f00-66e7-11e9-9550-73906c415dda.png "Chrome Dev Tools Network Tab - Click to view larger image")

# Example Optimisation

For example, consider the footer image:
https://www.clubsodaguide.com/images/footer-image-dab93b349117b0e1620b735d04f3ea12.jpg?vsn=d
Is an _incredibly_ high resolution (3000 × 2000 pixels) professional quality photograph.
![image](https://user-images.githubusercontent.com/194400/56696249-325bd800-66e3-11e9-843d-60ff8040949d.png)
Zoom in on the current image to see how much detail there is:
![image](https://user-images.githubusercontent.com/194400/56696262-3ab41300-66e3-11e9-9d34-41aab6bfb7ad.png)
(_this is an absurdly high resolution for a website and especially so on a mobile-first site_)

Downloaded the file on my mac and inspected the metadata:
![image](https://user-images.githubusercontent.com/194400/56696343-7222bf80-66e3-11e9-82c9-bb2c267ed7ea.png)

Using the _free_ online service https://imagecompressor.com I simply dragged the saved image from my desktop into the browser and using the `default` options the image was compressed by 95%:
![image](https://user-images.githubusercontent.com/194400/56696418-a4342180-66e3-11e9-855e-3aebba247dfb.png)

![footer-image-dab93b349117b0e1620b735d04f3ea12-min](https://user-images.githubusercontent.com/194400/56696625-4c49ea80-66e4-11e9-9f97-62687d7eed96.jpg)
![image](https://user-images.githubusercontent.com/194400/56696669-697eb900-66e4-11e9-88e8-7de196198a6b.png)

I _manually_ experimented with the settings on https://imagecompressor.com and found that reducing the quality of the image to 28% of original, which resulted in a 97% file size saving did not have a naked-eye noticeable impact on the image:
![image](https://user-images.githubusercontent.com/194400/56696726-9501a380-66e4-11e9-8ef5-6d7cfe9c3d6b.png)
![footer-image-dab93b349117b0e1620b735d04f3ea12-min-quality-28](https://user-images.githubusercontent.com/194400/56696811-db570280-66e4-11e9-9594-13e7d217633e.jpg)

Searching the code on GitHub for "footer-image" we see that it's linked in [`assets/css/app.css`](https://github.com/club-soda/club-soda-guide/blob/6d9df18d20b0beb0bcd729ba43c68a8af3c71840/assets/css/app.css):
https://github.com/club-soda/club-soda-guide/search?q=footer-image&unscoped_q=footer-image
![image](https://user-images.githubusercontent.com/194400/56697793-a39d8a00-66e7-11e9-9c25-48f4a33420bf.png)

The actual `app.css` file is quite large so use the browser's find function
to locate the references to `footer-image`:
![image](https://user-images.githubusercontent.com/194400/56698667-a2219100-66ea-11e9-8128-b30512eb4dbc.png)
https://github.com/club-soda/club-soda-guide/blob/6d9df18d20b0beb0bcd729ba43c68a8af3c71840/assets/css/app.css#L492-L494

The actual image is in the [`assets/static/images`](https://github.com/club-soda/club-soda-guide/tree/master/assets/static/images) folder: https://github.com/club-soda/club-soda-guide/blob/master/assets/static/images/footer-image.jpg
![image](https://user-images.githubusercontent.com/194400/56697863-e19aae00-66e7-11e9-9726-fd5b2a20f5cc.png)
In this screenshot we can only see a tiny fraction of the image because GitHub renders images in their full resolution by default. 

# Todo

+ [x] Go through each image that are used on the home page of the Guide Website.
  + [ ] Download the image to be optimised
  + [ ] Upload it to https://imagecompressor.com
  + [ ] Experiment with the quality slider to determine the optimal quality/file-size tradeoff.
  + [ ] Download the compressed image from https://imagecompressor.com
  + [ ] Upload the image into the [`assets/static/images`](https://github.com/club-soda/club-soda-guide/tree/master/assets/static/images) folder on GitHub (_see above_)
  + [ ] Update the location in the code where the original (_large file was referenced_) 

![image](https://user-images.githubusercontent.com/194400/56697973-3807ec80-66e8-11e9-9d6a-829bbd2fedc3.png)

@jessyclubsoda / @jussi-club-soda we feel that the image optimisation task _can_ be performed by _anyone_ (_it does not require a developer_), and as such the CS site admin team can save budget by doing the work using the free online tool and following the instructions I've outlined above. We can assign this task to a member of the @dwyl team if you prefer. (_please simply prioritise this issue and assign it to the appropriate person for completion_).

**Comment by nelsonic** [comment]
# Making the [Change](https://youtu.be/PivWY9wn5ps)

_After_ following the steps above to optimise an image, follow these steps to make the change!
> **Note**: there are programs/apps that can do _even_ better image optimisation/compression,
if you are feeling conscientious, read and follow these steps:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization



## 1. Upload the Optimised Image

+ [x] Upload the optimised footer image:
  + [x] navigate to: https://github.com/club-soda/club-soda-guide/tree/master/assets/static/images
<img width="1125" alt="github-clubsoda-images-upload-files" src="https://user-images.githubusercontent.com/194400/56700000-dc416180-66ef-11e9-970d-bb9f6b6a824c.png">

  + [x] Click on "Upload Files" 
  + [x] Drag and drop the file from your computer into the GitHub window:

<img width="1125" alt="github-clubsoda-images-upload-files-commit-changes" src="https://user-images.githubusercontent.com/194400/56700118-773a3b80-66f0-11e9-85da-8f021a01d4a9.png">

  + [x] Add a _descriptive_ Commit Message linking to the issue number e.g: #562 
  + [x] Click the "Create a **new branch**" radio button and give your branch a descriptive name.
  + [x] Click on "Propose changes" button. 
  + [x] Create a pull request e.g: #564 and _assign_ it to a member of the team for review:

<img width="1125" alt="github-clubsoda-images-create-pull-request" src="https://user-images.githubusercontent.com/194400/56700303-79e96080-66f1-11e9-8d1e-fe6b590c2833.png">

If you view the "files changed" tab in the pull request you will see the file you just uploaded:
![image](https://user-images.githubusercontent.com/194400/56700370-c765cd80-66f1-11e9-91dc-2bd3e26ecbcf.png)
For security reasons, GitHub does not display image files in Pull Requests 
hence the "Binary file not shown." however it will be visible once the PR is _merged_. 

> **Note**: you can upload multiple images in "bulk" on GitHub so step can be done _once_ for all images.

## 2. Update the `app.css` file which links to the `footer-image.jpg`

+ [x] Update the 3 instanced of `footer-image` in `app.css`
  + [x] Navigate to: https://github.com/club-soda/club-soda-guide/blob/master/assets/css/app.css
  + [x] Click on the Pencil icon to edit the file:

<img width="1102" alt="github-clubsoda-images-edit-app-css" src="https://user-images.githubusercontent.com/194400/56700468-4bb85080-66f2-11e9-94e7-25f21c79f0d2.png">

  + [x] Use the browser's "find" function (e.g: **`⌘ + F`**) to locate the file in the `app.css` file:

<img width="1211" alt="github-clubsoda-images-find-footer-in-css" src="https://user-images.githubusercontent.com/194400/56700629-2b3cc600-66f3-11e9-9fe2-c7ceec40b21c.png">

  + [x] make the necessary update to the file name.
e.g: in the case of the footer, from `footer-image.jpg` to **`footer-image-min.jpg`**

<img width="1335" alt="github-clubsoda-images-find-footer-in-css-updated" src="https://user-images.githubusercontent.com/194400/56700727-98e8f200-66f3-11e9-9b82-09216cee54bb.png">

+ [x] Scroll to the bottom of the page and follow the same steps as above to create a pull request for the changes you've made to `app.css`:

<img width="1132" alt="github-clubsoda-images-final-pull-request" src="https://user-images.githubusercontent.com/194400/56700841-2debeb00-66f4-11e9-8446-94323060353b.png">


## 3. Create a Pull Request to Commit the Image Update

+ [x] Create a pull request for the change made and assign it to a different member of the team for review. e.g: #565

![image](https://user-images.githubusercontent.com/194400/56700902-7f947580-66f4-11e9-81ec-5ffe9d432edb.png)

## 4. Review on Staging

+ [x] Once the _two_ pull requests (_one for the file upload and the other for the CSS or Template change_) have been reviewed and merged (_by a different member of the team_), visit the _staging_ site to see the changes reflected. https://club-soda-guide-staging.herokuapp.com

https://club-soda-guide-staging.herokuapp.com/images/footer-image-min.jpg
![image](https://user-images.githubusercontent.com/194400/56701019-28db6b80-66f5-11e9-9497-67d0e1dab904.png)

Confirm that the correct footer image (`footer-image-min.jpg`) is being used on the page:
<img width="1559" alt="github-clubsoda-images-end-result" src="https://user-images.githubusercontent.com/194400/56701320-668cc400-66f6-11e9-8057-bc86a82ff0ac.png">

We just saved thousands of people _megabytes_ of bandwidth and seconds of time. 🎉 
Do that for all the remaining large images and you'll have done a good deed for society! 🥇 

If you want to take this a step further, re-size the images on your computer before uploading them to the online compressor tool using "Paint" or Photoshop if you have them.

**Comment by nelsonic** [comment]
After updating footer image (_which was the biggest image on the homepage - and present on all pages so it would load on any "deep linked" page_), the "lighthouse score" _jumped_ from **87** to **97** on staging: https://club-soda-guide-staging.herokuapp.com because the page loads _that_ much faster:

![image](https://user-images.githubusercontent.com/194400/56701603-dea7b980-66f7-11e9-8a73-64c791fe61c9.png)

This was the "lowest hanging fruit" in terms of image optimisation, but it's certainly not the _only_ image that can be optimised. There are at _least_ 10 images on the home page over **200kb** which can/should all be cut down by 95%+ to give a _considerably_ faster page loading time.

In addition to all these images, the brand images should be optimised ***`before`*** being uploaded on the the website to ensure that the brand pages load as fast as possible.

@jussi-club-soda / @jessyclubsoda please see my comment above about prioritising the task of further image optimisation. Thanks. 🌻

**Comment by jessyclubsoda** [comment]
Thanks for this @nelsonic ! I'm happy to take the lead on this

**Comment by nelsonic** [comment]
@jessyclubsoda good news: with your image optimisations you've more than doubled the page speed (_halved the loading time_) 🎉  

![image](https://user-images.githubusercontent.com/194400/56954586-0c955f80-6b37-11e9-9bb6-357cd846b81d.png)

The lighthouse report has improved:
![image](https://user-images.githubusercontent.com/194400/56954544-ec65a080-6b36-11e9-9b86-e2fe97e08fb1.png)

But there are still areas for potential improvement.
![image](https://user-images.githubusercontent.com/194400/56954653-377fb380-6b37-11e9-9bb4-32aae53f4c79.png)

The _second_ item in the list "***Properly size images***" is the one I would tackle next.
This is just a matter of reviewing the pixel dimensions of the images and re-sizing them to the appropriate size (_without loss of quality_). Preferably create a new/separate issue e.g: "Resize Images" and perform a similar checklist.

**Comment by jessyclubsoda** [comment]
Great news @nelsonic ! I'll look into that

I also ran a Lighthouse report on our of brand pages because they seem notably slower
![image](https://user-images.githubusercontent.com/49029914/56955469-6b5bd880-6b39-11e9-835d-15bd0f3642d0.png)

![image](https://user-images.githubusercontent.com/49029914/56955490-829ac600-6b39-11e9-9296-cda7310f1cd9.png)

Do you have any suggestions with working to improve these?

**Comment by nelsonic** [comment]
@jessyclubsoda yes, we should open a _separate_ issue for Text Compression: https://github.com/club-soda/club-soda-guide/issues/575


But the _images_ on the brand page in question are all rather large too.
![image](https://user-images.githubusercontent.com/194400/56956272-95ae9580-6b3b-11e9-9b3c-fb70275fb2fa.png)

We may need to find a more _sustainable_ solution to the image optimisation,
but for now, if you want to download, optimise and re-upload any of the images on the Heineken page (_including any of the drink images_) to improve the speed, that will give the page a boost.
