### ISSUE TITLE
Enable Text Compression in Phoenix

### ISSUE THREAD

**Issue by nelsonic** [club-soda/club-soda-guide#575]
As part of our performance optimisation (enhancement) quest, @jessyclubsoda noted that the brand page: https://www.clubsodaguide.com/brands/heineken listed "**Enable text compression**"
as the highest priority:

![cs-brand-page-lighthouse-score](https://user-images.githubusercontent.com/194400/56956067-00130600-6b3b-11e9-8e1b-6f1fd564064a.png)

# Todo
+ [x] "**Enable text compression**" for Phoenix:
https://til.hashrocket.com/posts/63dvv2huk4-enable-gzip-for-all-phoenix-responses
+ [x] Create Pull Request
+ [x] Confirm working on Staging

**Comment by nelsonic** [comment]
Lighthouse report on staging for https://club-soda-guide-staging.herokuapp.com/brands/heineken
![image](https://user-images.githubusercontent.com/194400/56962387-59386500-6b4e-11e9-8f85-ae27685814a9.png)
