### ISSUE TITLE
Clarify static pages documentation

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#579]
@jussi-club-soda got in touch with me to ask about documentation for how to create static pages, so I feel this section of the [User Guide/Documentation](https://github.com/club-soda/club-soda-guide#user-admin-guide) needs a little TLC!

## Tasks
+ [ ] Create separate section for Static Pages (with linkable title)
+ [ ] Review and update wording to make sure it makes sense in its own section
+ [ ] Confirm it's up to date with #535

**Comment by iteles** [comment]
Took a few screenshots to update the documentation whilst doing this:

![Screen Shot 2019-05-20 at 12 48 27](https://user-images.githubusercontent.com/4185328/58019686-05da8680-7afe-11e9-938e-2e9d8dd76aa8.png)

![image](https://user-images.githubusercontent.com/4185328/58051802-12d19700-7b4b-11e9-9937-6cf773b6e844.png)

![image](https://user-images.githubusercontent.com/4185328/58052152-026dec00-7b4c-11e9-9279-c89261a23fe1.png)

![image](https://user-images.githubusercontent.com/4185328/58056678-e6714700-7b59-11e9-8e76-bf248de4b760.png)

![drink-types](https://user-images.githubusercontent.com/4185328/58056981-18cf7400-7b5b-11e9-9f35-6091922262a2.png)

![image](https://user-images.githubusercontent.com/4185328/58057204-fe49ca80-7b5b-11e9-87fd-ec21abfde37c.png)

![image](https://user-images.githubusercontent.com/4185328/58057459-da3ab900-7b5c-11e9-8c48-98bd9bd46f3c.png)

**Comment by iteles** [comment]
@jessyclubsoda This one's a little more subjective to 'test' but I've updated the documentation with a few more headlines and re-ordered the information to be hopefully more intuitive here: https://github.com/club-soda/club-soda-guide

If you could take a look through and let me know if you'd like anything else to be added to the README, that would be grand!

**Comment by jessyclubsoda** [comment]
Looks great! Thanks @iteles 

One question - 
![Tab headings](https://user-images.githubusercontent.com/49029914/58484783-ac580480-815a-11e9-9cfd-775ba4a9d841.png)
This doesn't seem to actually work. The tab headings always say 'Club Soda Guide' regardless of what I change the Browser Title too

**Comment by iteles** [comment]
@jessyclubsoda Ah yes, that's a bug, could you please open it as a separate issue?
