### ISSUE TITLE
Cookies & GDPR

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#82]
**UPDATED tasks in light of final requirements**

As a site owner,
I would like to use cookies to enhance the experience of my users and to collect analytics
So that our customers return to the website and we have data to know how to continuously improve it.

_This is currently a holding issue so that we are aware that we will need to do a piece of work on this once it's more defined._

## Tasks
+ [x] Add wording to the cookie policy to explain use of cookies for (note: at the time of writing, location data is not stored in cookies to the best of my knowledge and we do not need user login functionality):
  + Third party analytics
  + Keeping venues logged in
+ [x] Add wording to privacy policy around how users can request deletion of their data (this is only really applicable to venue managers) by emailing Club Soda
+ [x] Ensure GDPR compliant consent is requested from venue managers who sign up in #53 

Note: We are not saving any personal data to Amazon S3 so this does not need to be EU based.

**Comment by jessyclubsoda** [comment]
So just to clarify on this - we need to draft a cookies policy, a privacy policy and Terms of Service?

**Comment by iteles** [comment]
@jessyclubsoda You could have your privacy and cookie policies in the same page but I would recommend you split out your terms of service. We can get these linked in the footer for you too!

**Comment by iteles** [comment]
@jessyclubsoda Any luck crafting this content? 😊

**Comment by jessyclubsoda** [comment]
@iteles It's all done! Once we move the most recent updates from staging to live I'll be able to add it to the site because the Static Pages bug will be fixed !

**Comment by RobStallion** [comment]
Currently, the app allows logged in users to list a new venue and it's owner...
![image](https://user-images.githubusercontent.com/15571853/56299081-42941600-612b-11e9-991a-1961e7ba580d.png)

If we are going to add the accept Ts&Cs here then it may be best to stop logged in users from doing this step as they could be accepting the conditions on someone else's behalf.

Or we could make it so that logged in users can only list venues related to themselves to avoid this potential issue.

**Comment by iteles** [comment]
@jessyclubsoda Would it be practical to only allow venue owners who are logged in to create venue listings only related to themselves?

In UI terms this would mean that we remove the email field (and related checkboxes) from the form if a venue manager is already logged in and simply automatically attach this venue to the logged in user.  
We'd have to also change the messaging a little but I think this should be changed for all people creating venues anyway - 'Please only use this for if you own or manage **the** venue **you are creating a listing for** - if you are...'

**Comment by jessyclubsoda** [comment]
@iteles Would this allow a venue owner to host multiple venues? Because I think this would be fine as long as that was possible e.g. if a chain of venues wants to have all of them run by one manager

**Comment by iteles** [comment]
@jessyclubsoda Yes, so it would function a bit like this:
+ If you're not logged in, you can create a new venue with your email address as normal
+ If you _are_ logged in as a venue manager, you can create a new venue but you won't see the email address field and the venue will automatically be associated to the email address you're logged in as

This means that there's one user, but multiple venues (as opposed to multiple users with the same email address).

**Comment by jessyclubsoda** [comment]
Sounds good to me!

**Comment by RobStallion** [comment]
Sorry about the timing of this but just had another thought about around consenting to Ts & Cs. 

`Site admins` can not create `venue owners` and add them to a venue...
![image](https://user-images.githubusercontent.com/15571853/56424297-8f046080-62a7-11e9-8790-7640baa2e7a8.png)

![image](https://user-images.githubusercontent.com/15571853/56424310-988dc880-62a7-11e9-8961-b2aaecc6a711.png)

These users will skip the consent section as they will created by a site admin. 

I have added the checkboxes to the set password page now as well but only for users who are not verified....

(only none verified users will see checkboxes)
![image](https://user-images.githubusercontent.com/15571853/56424597-e3f4a680-62a8-11e9-80e9-6f4316f01bee.png)

As `venue owners` that are created by `site admins` need to follow the link that they receive in the email in order to log in, this will make sure that they have also agreed to the Ts&Cs

**Comment by iteles** [comment]
Good thinking @RobStallion !
