### ISSUE TITLE
Who are the users of the website? > Create Personas

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#93]
Moved these questions from @nelsonic to their own issue from https://github.com/club-soda/club-soda-guide/issues/5#issuecomment-422048098 so that we are able to discuss each topic separately:

## 1. Users?

1. Who are the "**users**" of the Website? 
  + The "**Piqued Drinker**" - someone who is _already_ aware and or has a desire to be more mindful of their drinking. The _vast_ majority users of the website are the "mindful drinkers". 
    + Are the drink buyers further segmented? 
    e.g: http://howtorunapub.co.uk/uk-pub-customer-demographics-behaviours/
      + Students / "Young & Free"
      + Nesting couples (no kids)
      + Affluent Young Professionals (no kids)
      + Families (with kids)
      + Mums & Dads (not taking kids to pub)
      + "Empty Nesters" (older people whose kids have left home) 
  + Venue/**Pub Owner**/Manager - the people for whom incremental patrons (customers) will have a _meaningful_ impact on bottom line.
  + Product/Brand Manager
  + Club Soda _Admin_

> Do we have a "persona" for each type of user for the Website or at least clearly defined "roles"?
(_so that we can write user stories for each one? and can we have a **`label`** fore each user?_)
Are each of these these users "active" or "passive" (_do they **create** or simply **consume** content_?) do we _want_ them to create content? (_will that drive revenue for Pubs/Brands and "CS"_)

<hr />

# Todo 

+ [x] Create a Person Card for each of the "users" of the CS app (_@jussi-club-soda's comment below_)
  > Note: _initially_ we only need **one** Persona for consumers; we can create more as required.
  + [x] **Sketch** a simple avatar/character for each Persona. e.g:
![image](https://user-images.githubusercontent.com/194400/45924840-acd03980-bf01-11e8-976c-4a6770c7798c.png)
  + [x] ***Name*** each Persona (_preferably an **alliteration**_) e.g: 
    + [x] ***Connor*** or ***Cora*** the "Consumer"
    + [x] ***Peter*** or ***Puja*** the "Pub Manager" 
    + [x] ***Diego*** the **Drink Brand/Product Manager/Owner** 
    + [x] [***Amanda***](https://youtu.be/iKZTOXkD22c?t=3s) the "CS Admin"
    + [x] I'm _fairly sure_ someone `else` can derive better names, go for it! 
+ [x] ***Describe*** the Persona's **Facts**:
  + [x] **Age** (_either **exact** or **range**_) 
  + [x] **Background** (_one liner_)
  + [x] **Motivations**
+ [x] **_Pain_ Points**? e.g: with Alcohol products and with _finding_ products/venues using the CS site/app.
+ [x] ***Goals***? e.g: cut down on alcohol for `{reason}`
  + [x] ***Why*** do they ***need*** the CS website/app in order to achieve their Goal?

@Cleop please _estimate_ how long it will take to create the Personas
and work with @ctrembath on creating them. 
Our objective is to tell the _story_ of each of the users in card form to help:
+ All _current_ (& future) team members and (_internal_) stakeholders 
to have a _clear_ understanding of and empathy for the "users".
+ Funders/Customers to _understand_ the mission of the CS Product 
and have _confidence_ that CS are the "_right_" team to _solve_ the challenge.

**Comment by nelsonic** [comment]
@jussi-club-soda **_thank_** you for adding these detailed user types. 👍 

@iteles I have updated the issue description with a Todo List (Task) to create Personas.
This will be an _exceptionally_ worthwhile investment over the lifecycle of the CS Site/App
for clearly communicating with current/future internal/external team-members/stakeholders. 

@Cleop please take a look at this task and estimate it. Thanks!

**Comment by jussi-club-soda** [comment]
We will be doing some of this today at a workshop with beer producers - we can probably recycle some of the outputs from there.

But this sounds to me like something we should have already done before/during the design sprint? 

How much value is it going to add now? Especially if we only do 1 consumer persona - there are so many of them that I struggle to see the value of just doing 1 (which one? and what about all the other kinds?)...

**Comment by nelsonic** [comment]
@jussi-club-soda **_great_ news*** that you are doing the workshop with beer producers and there might be some re-useable persona data we can make into more personas for the product development. 🎉 

To _clarify_ the task above (_assigned to @Cleop_) is to "timebox" persona creation. ⏱ 
By **_intentionally_ limiting** the Consumer persona to **One** (_initially_) we _focus_ our attention
on "_understanding_" (_empathising with_) that ***one user*** and "_solving_" their problem.
We then take the implementation of the feature (_solution_) and _test_ it with the user. 

Even _if_ we have enough data _now_ to create 10+ **`Consumer`**  Personas, 
it would be a _distraction_ (_in the short-term_) because we _cannot_ solve _everyone's_ problem at once.

We will _absolutely_ be adding to the **`Consumer`**  Personas cards over time as we _expand_ 
Our objective for _this_ Task is to:
+ **Define** the "_lowest hanging fruit_" user who has a _particular_ "pain point" or "goal" we can address _immediately_. e.g: "_**`Cora`** is **`47`**, works in Finance and wants to **`cut down`** because of **`{reason}`**._"
+ **Capture** their details in a Persona Card (_print cards so we can put them on the wall!_)
+ **Target** user stories to the Persona (_so that everyone in the team is clear who we are building for_)
+ **Build** the Sprint feature(s) with the Persona in mind.
+ **Find** "test subjects" who fit the Persona and ask them to UX-test the feature(s) once built.
+ **UX-Test** the features and get _qualitative_ feedback from the (_real/prospective_) user. 
  + Was she able to accomplish her mini-goal (_as per the script/instructions_) using the site/app?
  + Did she "give up" because the UX was frustrating?
  + How likely is she to _re-use_ the product or _recommend_ it to someone `else` ?
  + What improvements did we spot while watching her (_attempt to_) _use_ product/feature?
    + Are those improvements _already_ captured in the backlog? (_can we work on them next sprint?_)

This is a _much_ more _focussed_ way of building as we have a _precise_ definition of the user,
as opposed to a _nebulous_ "_person who wants to cut down on their alcohol consumption_".

As for having the personas _before/during_ the Design Sprint, we _agree_. 
There appears to have been a lack of clarity (_possibly stemming from a miss-communication_), we _thought_ the personas _already existed_, but as it happens, they are not (yet) "_formalised_" into "cards", therefore we are "filling in the gap" _now_. 
This is _not_ to say that the efforts of the Design Sprint were in _any_ way "wasted";
the outcome/output of the Design Sprint is _super_ valuable "high level" UX/design 
which we _will_ be using throughout the dev lifecycle. 
What we need now is to _focus_ on building the _increments_ of useful functionality 
with a _specific_ target user (Persona) in mind. 

Having Personas now (_and for the life-time of the project_) adds _immense_ value.
Focussing on ***one*** **`Consumer`** _first_ is just a way of being _targeted_.
In 6 months time you will have _all_ the **`Consumers`** (_probably 30+_) captured/codified.
We (@dwyl) only need to help with defining the first few to get the _initial_ features/functionality 
built & tested before launch in October. We can certainly _help_ with defining _many_ more personas,
but we _must_ be "strict" now and only focus on a _single_ **`Consumer`**. 
Thanks! ✨

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/46004041-d5933300-c0a9-11e8-9c97-c7ea0ad38d9e.png)
 ![image](https://user-images.githubusercontent.com/16775804/46004238-49354000-c0aa-11e8-801b-858d137f6b1b.png)
 ![image](https://user-images.githubusercontent.com/16775804/46004426-cb256900-c0aa-11e8-8faa-31878125a4d4.png)
 ![image](https://user-images.githubusercontent.com/16775804/46004730-7c2c0380-c0ab-11e8-96b1-267bdc416001.png)

**Comment by Cleop** [comment]
Here is a printable pdf of the personas so that you can print them and put them on the wall at CS HQ:

[Club Soda - User Personas.pdf](https://github.com/club-soda/club-soda-guide/files/2415030/Club.Soda.-.User.Personas.pdf)
